project:
  type: website
  output-dir: _site

website:
  title: "Glider Reporter"
  navbar:
    left:
      - href: data_intake.qmd
        text: Data Intake
      - href: function_explorer.qmd
        text: Function Explorer
      - href: report_builder.qmd
        text: Report Builder

format:
  html:
    toc: true
